# Auto-generated paths file
# All paths are defined as uppercase constants

__DIR = "images"
__DIR_GOLDENBALLON = "images/goldenballon.png"
BUTTONS_DIR = "images/buttons"
BUTTONS_DIR_BUTTONCLAIM = "images/buttons/buttonClaim.png"
BUTTONS_DIR_BUTTONLATESTSAVE = "images/buttons/buttonLatestSave.png"
BUTTONS_DIR_BUTTONPLAY = "images/buttons/buttonPlay.png"
BUTTONS_DIR_BUTTONSTART = "images/buttons/buttonStart.png"
BUTTONS_DIR_BUTTONX = "images/buttons/buttonX.png"
# BUTTONS
BUTTONS_MAP_DIR = "images/buttons/map"
BUTTONS_MAP_DIR_BUTTONADVANCED = "images/buttons/map/buttonAdvanced.png"
BUTTONS_MAP_DIR_BUTTONADVANCEDSELECTED = "images/buttons/map/buttonAdvancedSelected.png"
BUTTONS_MAP_DIR_BUTTONBEGINNER = "images/buttons/map/buttonBeginner.png"
BUTTONS_MAP_DIR_BUTTONBEGINNERSELECTED = "images/buttons/map/buttonBeginnerSelected.png"
BUTTONS_MAP_DIR_BUTTONCHANGEHERO = "images/buttons/map/buttonChangeHero.png"
BUTTONS_MAP_DIR_BUTTONCLICKTOUNLOCK = "images/buttons/map/buttonClickToUnlock.png"
BUTTONS_MAP_DIR_BUTTONDIFICULTIES = "images/buttons/map/buttonDificulties.png"
BUTTONS_MAP_DIR_BUTTONEXPERT = "images/buttons/map/buttonExpert.png"
BUTTONS_MAP_DIR_BUTTONEXPERTSELECTED = "images/buttons/map/buttonExpertSelected.png"
BUTTONS_MAP_DIR_BUTTONINTERMEDIATE = "images/buttons/map/buttonIntermediate.png"
BUTTONS_MAP_DIR_BUTTONINTERMEDIATESELECTED = "images/buttons/map/buttonIntermediateSelected.png"
BUTTONS_MAP_DIR_BUTTONLEFTARROW = "images/buttons/map/buttonLeftArrow.png"
BUTTONS_MAP_DIR_BUTTONRETURN = "images/buttons/map/buttonReturn.png"
BUTTONS_MAP_DIR_BUTTONRIGHTARROW = "images/buttons/map/buttonRightArrow.png"
# BUTTONS
BUTTONS_MAPDIFFICULTY_DIR = "images/buttons/mapDifficulty"
BUTTONS_MAPDIFFICULTY_DIR_BUTTONEASY = "images/buttons/mapDifficulty/buttonEasy.png"
BUTTONS_MAPDIFFICULTY_DIR_BUTTONHARD = "images/buttons/mapDifficulty/buttonHard.png"
BUTTONS_MAPDIFFICULTY_DIR_BUTTONMEDIUM = "images/buttons/mapDifficulty/buttonMedium.png"
# BUTTONS
BUTTONS_MAPMODES_DIR = "images/buttons/mapModes"
BUTTONS_MAPMODES_DIR_BUTTONALTERNATEBLOONSROUNDS = "images/buttons/mapModes/buttonAlternateBloonsRounds.png"
BUTTONS_MAPMODES_DIR_BUTTONAPOPALYPSE = "images/buttons/mapModes/buttonApopalypse.png"
BUTTONS_MAPMODES_DIR_BUTTONCHIMPS = "images/buttons/mapModes/buttonChimps.png"
BUTTONS_MAPMODES_DIR_BUTTONDEFLATION = "images/buttons/mapModes/buttonDeflation.png"
BUTTONS_MAPMODES_DIR_BUTTONDOUBLEHPMOABS = "images/buttons/mapModes/buttonDoubleHPMoabs.png"
BUTTONS_MAPMODES_DIR_BUTTONHALFCASH = "images/buttons/mapModes/buttonHalfCash.png"
BUTTONS_MAPMODES_DIR_BUTTONIMPOPPABLE = "images/buttons/mapModes/buttonImpoppable.png"
BUTTONS_MAPMODES_DIR_BUTTONMAGICMONKEYSONLY = "images/buttons/mapModes/buttonMagicMonkeysOnly.png"
BUTTONS_MAPMODES_DIR_BUTTONMILITARYONLY = "images/buttons/mapModes/buttonMilitaryOnly.png"
BUTTONS_MAPMODES_DIR_BUTTONPRIMARYONLY = "images/buttons/mapModes/buttonPrimaryOnly.png"
BUTTONS_MAPMODES_DIR_BUTTONREVERSE = "images/buttons/mapModes/buttonReverse.png"
BUTTONS_MAPMODES_DIR_BUTTONSANDBOX = "images/buttons/mapModes/buttonSandbox.png"
BUTTONS_MAPMODES_DIR_BUTTONSTANDARD = "images/buttons/mapModes/buttonStandard.png"
BUTTONS_MAPMODES_DIR_POPUPOVERWRITE = "images/buttons/mapModes/popupOverwrite.png"
# Desktop
DESKTOP_DIR = "images/desktop"
DESKTOP_DIR_BTD6_ICON = "images/desktop/btd6_icon.png"
DESKTOP_DIR_BTD6_LAUNCH = "images/desktop/btd6_launch.png"
DESKTOP_DIR_DESKTOP = "images/desktop/desktop.png"
# Rewards
REWARDS_DIR = "images/rewards"
REWARDS_DIR_DAILYCHEST = "images/rewards/dailyChest.png"
REWARDS_DIR_DAILYCHESTCHRISMAS = "images/rewards/dailyChestChrismas.png"
REWARDS_DIR_DAILYCHESTOPENED = "images/rewards/dailyChestOpened.png"
REWARDS_DIR_DAILYCHESTOPENEDCHRISMAS = "images/rewards/dailyChestOpenedChrismas.png"
REWARDS_DIR_REWARD1 = "images/rewards/reward1.png"
REWARDS_DIR_REWARD2 = "images/rewards/reward2.png"
REWARDS_DIR_REWARD3 = "images/rewards/reward3.png"
REWARDS_DIR_REWARDINSTAMONKEY = "images/rewards/rewardInstaMonkey.png"
REWARDS_DIR_REWARDMONEY = "images/rewards/rewardMoney.png"
# Screens
SCREENS_DIR = "images/screens"
SCREENS_DIR_DAILYREWARDCOLLECTEDSCREEN = "images/screens/dailyrewardCollectedScreen.png"
SCREENS_DIR_DAILYREWARDCOLLECTEDSCREENCHRISMAS = "images/screens/dailyrewardCollectedScreenChrismas.png"
SCREENS_DIR_LOADINGSCREEN = "images/screens/loadingScreen.png"
SCREENS_DIR_MAINMENUSCREEN = "images/screens/mainmenuScreen.png"
SCREENS_DIR_MAINMENUSCREENCHRISMAS = "images/screens/mainmenuScreenChrismas.png"
SCREENS_DIR_SELECTSCREEN = "images/screens/selectScreen.png"
SCREENS_DIR_STARTSCREEN = "images/screens/startScreen.png"
